### ISSUE TITLE
What's Happening section - "Learn More" buttons off the cards

### ISSUE THREAD

**Issue by bhumika-gupta** [PuMProfessionals/pump-web-v2#57]
<img width="1259" alt="Screen Shot 2021-08-15 at 11 26 25 PM" src="https://user-images.githubusercontent.com/63598253/129600246-f2ab94e6-e1b7-4eaa-bdcc-3f30e22e523c.png">

Chrome browser 1440 x 764

**Comment by realsimonwu** [comment]
Fixed in current release build for me
