### ISSUE TITLE
About Us - text overflowing 

### ISSUE THREAD

**Issue by bhumika-gupta** [PuMProfessionals/pump-web-v2#63]
<img width="1260" alt="Screen Shot 2021-08-19 at 8 30 47 PM" src="https://user-images.githubusercontent.com/63598253/130160806-d607194c-b0bd-4117-8887-86601d19b887.png">

<img width="1410" alt="Screen Shot 2021-08-19 at 8 31 54 PM" src="https://user-images.githubusercontent.com/63598253/130160870-9542fb29-7fe3-4142-9b56-4cdf49e4339d.png">

Chrome browser 1440 x 764

**Comment by realsimonwu** [comment]
Resolved in latest release build for me
