### ISSUE TITLE
Links to mentor & mentee applications on PowerUp Mentorship Program event page

### ISSUE THREAD

**Issue by bhumika-gupta** [PuMProfessionals/pump-web-v2#76]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/63598253/132251296-ef399955-126b-4c36-abac-4aec54a21c71.png">

In my opinion, I think that these links should open up in a new tab, since the user is being directed to filling out a form and if it opens in the same tab, then it would be harder to return to the PuMP website and they would have to risk losing their progress. Not sure if this is a big issue but from a UX standpoint I think it is definitely worth pointing out.

**Comment by xsharonhe** [comment]
Addressed to fix: https://github.com/PuMProfessionals/pump-web-v2/pull/87
