### ISSUE TITLE
/resources/blog Too wide on mobile 

### ISSUE THREAD

**Issue by hirundinidae** [PuMProfessionals/pump-web-v2#81]
The blog list page is too wide (horizontal scroll bar appears) at sizes smaller than ~1050px. Shows up on Firefox on Android and in responsive design mode. 

<img src="https://user-images.githubusercontent.com/65516245/140675588-480143bb-1c9b-4073-ba20-d7893ea8abb9.png" width=500>

<img src="https://user-images.githubusercontent.com/65516245/140675705-bda0102b-bc81-418d-813b-ee1fc9a89633.png" width=300>

https://user-images.githubusercontent.com/65516245/140676128-eabbdb56-eca4-4e4f-9274-62e666b9643e.mp4

**Comment by xsharonhe** [comment]
fix? commit: 17001ca

**Comment by xsharonhe** [comment]
https://github.com/PuMProfessionals/pump-web-v2/pull/97

**Comment by xsharonhe** [comment]
feel free to repoen if it doesn't fix in a week
