### ISSUE TITLE
Increase width of contact form on mobile 

### ISSUE THREAD

**Issue by hirundinidae** [PuMProfessionals/pump-web-v2#82]
The contact form could probably use less padding/margins on the sides on mobile. I would increase the width of the card at around 500-600 pixels, otherwise the form is hard to use on mobile screens (email, name start to get cut off) 

<img src="https://user-images.githubusercontent.com/65516245/140687225-fafd2fa1-5b7e-48e9-ba9e-befe1ccde167.png" width=300>

**Comment by xsharonhe** [comment]
Fix with: https://github.com/PuMProfessionals/pump-web-v2/pull/88
