### ISSUE TITLE
/resources/blog title image 

### ISSUE THREAD

**Issue by hirundinidae** [PuMProfessionals/pump-web-v2#83]
The graphic (person holding a stethoscope) is vertically compressed when the title is 1 line (1230+ px) vs 2 lines (900 to 1200 px) and on mobile (<900px). Checked on Firefox and Chromium 
<img src="https://user-images.githubusercontent.com/65516245/140688067-0e6b2dbf-d754-45cc-82e5-84649c089053.png" width=400>
<img src="https://user-images.githubusercontent.com/65516245/140688077-572667cd-489c-441b-b65a-03406b88c35f.png" width=500>
<img src="https://user-images.githubusercontent.com/65516245/140688079-573fa4ac-32ce-47fd-a2d8-27e87f3d2fa9.png" width=500>

**Comment by xsharonhe** [comment]
Fix with: https://github.com/PuMProfessionals/pump-web-v2/pull/88
