### ISSUE TITLE
Increase size of title text on mobile

### ISSUE THREAD

**Issue by hirundinidae** [PuMProfessionals/pump-web-v2#84]
The title text is quite small compared to the rest of the text on mobile 
<img src="https://user-images.githubusercontent.com/65516245/140688603-7d32cc03-71c8-44d4-a741-09963d4c8e13.png" width=300>
![image](https://user-images.githubusercontent.com/65516245/140688732-a9caa2b5-d26a-4114-95b3-c2bc0c9fd0d5.png)
If "PuMP Direct" is more important than "Filters" I think it should be larger (increase width+size of title text component)

**Comment by xsharonhe** [comment]
Fix with: https://github.com/PuMProfessionals/pump-web-v2/pull/88
