### ISSUE TITLE
PuMP Direct page - image not showing up

### ISSUE THREAD

**Issue by bhumika-gupta** [PuMProfessionals/pump-web-v2#92]
from PuMP Direct main page (not opportunity page)

University of Toronto's Youth Summer Medical Program:
<img width="904" alt="Screen Shot 2021-11-20 at 2 50 55 PM" src="https://user-images.githubusercontent.com/63598253/142739237-f23f91d3-802d-4ccf-8e1b-a7ed374db56a.png">

**Comment by xsharonhe** [comment]
Funny since this is working on dev environment.

**Comment by xsharonhe** [comment]
Finally fixed on production - not sure why it wasn't working but that was a major hassle.

**Comment by xsharonhe** [comment]
Commit ce66e19

**Comment by xsharonhe** [comment]
https://github.com/PuMProfessionals/pump-web-v2/pull/97
