### ISSUE TITLE
PuMP Direct Opportunities Images

### ISSUE THREAD

**Issue by bhumika-gupta** [PuMProfessionals/pump-web-v2#94]
A couple of images look a bit distorted/compressed throughout some of the opps

Medical First Responder – St. John Ambulance (https://release-2021-pumprofessionals-org.vercel.app/resources/opportunities/st-john-ambulance)
<img width="1440" alt="Screen Shot 2021-11-24 at 2 08 47 PM" src="https://user-images.githubusercontent.com/63598253/143299560-a682d776-8b75-4add-b366-7fb13853362c.png">

Belmont House Senior's Home - Volunteering
<img width="1440" alt="Screen Shot 2021-11-24 at 2 09 46 PM" src="https://user-images.githubusercontent.com/63598253/143299657-fa8373e6-03ac-463a-90c9-1613ec927113.png">

Circle of Care Senior Home – Volunteering
<img width="1439" alt="Screen Shot 2021-11-24 at 2 10 15 PM" src="https://user-images.githubusercontent.com/63598253/143299714-ea2fea32-75e2-403a-8e59-03b2920c596d.png">

Chartwell Retirement Home Positions
<img width="1440" alt="Screen Shot 2021-11-24 at 2 10 34 PM" src="https://user-images.githubusercontent.com/63598253/143299755-e5a55ac8-f711-46bc-bfdd-00b58cf846e0.png">

York University Spark Summer Program
<img width="1439" alt="Screen Shot 2021-11-24 at 2 11 15 PM" src="https://user-images.githubusercontent.com/63598253/143299840-06c1df02-1c2c-4a7e-9359-8e74e30e4a0e.png">

Summer Student Placement – WoodGreen Foundation
<img width="1440" alt="Screen Shot 2021-11-24 at 2 11 38 PM" src="https://user-images.githubusercontent.com/63598253/143299888-090477d3-a287-42d3-92aa-27a22a8c4835.png">

Volunteering – Scarborough Health Network
<img width="1440" alt="Screen Shot 2021-11-24 at 2 11 57 PM" src="https://user-images.githubusercontent.com/63598253/143299918-adcbc768-ca75-4651-8014-e7ec751d436c.png">

Discover Hopkins Programs
<img width="1439" alt="Screen Shot 2021-11-24 at 2 13 00 PM" src="https://user-images.githubusercontent.com/63598253/143300031-bca21b00-77ca-4dae-94e2-9a0a4fcc48a7.png">

I tried opening the image in a new tab and it looks normal so it's not the actual photo that's distorted/compressed
<img width="1440" alt="Screen Shot 2021-11-24 at 2 13 42 PM" src="https://user-images.githubusercontent.com/63598253/143300114-7c349e7a-ce93-4c86-8d43-7500aa46484c.png">

Safari browser 1440px x 930px

**Comment by xsharonhe** [comment]
Thank you for checking all of them! I don't think the sizes were changed ahead of time so these are awesome.

**Comment by xsharonhe** [comment]
fixed in #99
